#!/usr/bin/env python3
"""Export the exact DeepFilterNet2 ERB analysis and mask-expansion matrices.

The matrices are registered buffers of :class:`DeepFilterNet2`, so this tool
constructs the model through the same config reader as training instead of
reimplementing the filterbank.  The C runtime uses ``forward`` to build ERB
features and ``inverse`` to expand network ERB masks to FFT-bin gains.
"""

import argparse
import configparser
import hashlib
import json
import os
import struct

import numpy as np
import torch

from model import DeepFilterNet2
from train import read_model_config


_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def _write_matrix(fp, name, matrix):
    rows, cols = matrix.shape
    fp.write("static const float %s[%d][%d] = {\n" % (name, rows, cols))
    for row in matrix:
        fp.write("    {%s},\n" % ", ".join("%.9ef" % float(v) for v in row))
    fp.write("};\n\n")


def write_c_tables(config_path, out_path):
    """Emit the runtime C tables from the model's frozen ERB buffers.

    Grid-determined (not trained): generate once per grid, commit, and the
    runtime never rebuilds the filterbank. Layouts match df_common's
    accumulation loops: forward bin-major [n_bins][n_erb], inverse
    band-major [n_erb][n_bins]. DFN2 and DFN3 share the filterbank; the
    contract tests pin both models' buffers against this one header.
    """
    import configparser as _configparser

    import torch

    try:
        from .model import DeepFilterNet2
        from .train import read_model_config
    except ImportError:
        from model import DeepFilterNet2
        from train import read_model_config

    cfg = _configparser.ConfigParser()
    if not cfg.read(config_path):
        raise FileNotFoundError(config_path)
    with torch.no_grad():
        model = DeepFilterNet2(**read_model_config(cfg))
        forward = model.erb_fb.detach().numpy().astype('<f4')
        inverse = model.erb_inv.detach().numpy().astype('<f4')
    if forward.shape[0] < forward.shape[1]:
        forward = forward.T
    if inverse.shape[0] > inverse.shape[1]:
        inverse = inverse.T
    with open(out_path, 'w', encoding='utf-8') as fp:
        fp.write('/* Generated by export_erb_matrix.py --c-tables. '
                 'DO NOT EDIT.\n'
                 ' * Frozen DFN filterbank buffers (bins x bands forward, '
                 'bands x bins\n'
                 ' * inverse); grid-determined, committed once, never '
                 'rebuilt at runtime.\n'
                 ' * test_dfn2_contract.py pins these values against the '
                 'model buffers. */\n\n')
        _write_matrix(fp, 'dfn_erb_fwd', forward)
        _write_matrix(fp, 'dfn_erb_inv', inverse)
    return out_path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--config',
                        default=os.path.join(_SCRIPT_DIR, 'config.ini'))
    parser.add_argument('--model', default=None,
                        help='optional checkpoint; validates that exported buffers match it')
    parser.add_argument('--output-dir', default=None)
    parser.add_argument('--format', choices=('bin', 'npy', 'c', 'all'), default='all')
    parser.add_argument('--c-tables', default=None,
                        help='write the runtime dfn_erb_tables_gen.h from '
                             'the model construction (no checkpoint needed) '
                             'and exit')
    args = parser.parse_args()
    if args.c_tables:
        print(write_c_tables(args.config, args.c_tables))
        return

    cfg = configparser.ConfigParser()
    if not cfg.read(args.config):
        raise FileNotFoundError(args.config)
    model = DeepFilterNet2(**read_model_config(cfg)).eval()
    if args.model:
        checkpoint = torch.load(args.model, map_location='cpu', weights_only=False)
        model.load_state_dict(checkpoint['state_dict'], strict=True)

    # model buffers are (bands, bins); C tables are row-major (bins, bands).
    forward = model.erb_fb.detach().cpu().numpy().T.astype('<f4', copy=False)
    inverse = model.erb_inv.detach().cpu().numpy().T.astype('<f4', copy=False)
    n_bins, n_bands = forward.shape
    output_dir = args.output_dir or cfg.get('paths', 'output_dir', fallback='output')
    os.makedirs(output_dir, exist_ok=True)

    metadata = {
        'schema': 'dfn2-erb-matrix-v1',
        'sample_rate': cfg.getint('signal', 'sr'),
        'n_fft': cfg.getint('signal', 'n_fft'),
        'n_bins': n_bins,
        'n_bands': n_bands,
        'forward_layout': 'fft_bin_major[n_bins][n_bands]',
        'inverse_layout': 'fft_bin_major[n_bins][n_bands]',
        'forward_use': 'erb_power[band] = sum(power[bin] * forward[bin][band])',
        'inverse_use': 'bin_gain[bin] = sum(inverse[bin][band] * mask[band])',
    }
    if args.model:
        digest = hashlib.sha256()
        with open(args.model, 'rb') as stream:
            for chunk in iter(lambda: stream.read(1024 * 1024), b''):
                digest.update(chunk)
        metadata['checkpoint_sha256'] = digest.hexdigest()
    with open(os.path.join(output_dir, 'erb_matrix.json'), 'w', encoding='utf-8') as fp:
        json.dump(metadata, fp, indent=2, sort_keys=True)
        fp.write('\n')

    if args.format in ('bin', 'all'):
        path = os.path.join(output_dir, 'erb_matrix.bin')
        with open(path, 'wb') as fp:
            fp.write(struct.pack('<ii', n_bins, n_bands))
            fp.write(np.ascontiguousarray(forward).tobytes())
            fp.write(np.ascontiguousarray(inverse).tobytes())
        print(path)
    if args.format in ('npy', 'all'):
        np.save(os.path.join(output_dir, 'erb_forward.npy'), forward)
        np.save(os.path.join(output_dir, 'erb_inverse.npy'), inverse)
    if args.format in ('c', 'all'):
        path = os.path.join(output_dir, 'erb_matrix.h')
        with open(path, 'w', encoding='ascii') as fp:
            fp.write("/* Generated by DeepFilterNet2/export_erb_matrix.py. */\n")
            fp.write("#ifndef DFN2_ERB_MATRIX_GENERATED_H\n")
            fp.write("#define DFN2_ERB_MATRIX_GENERATED_H\n\n")
            fp.write("#define DFN2_ERB_MATRIX_BINS %d\n" % n_bins)
            fp.write("#define DFN2_ERB_MATRIX_BANDS %d\n\n" % n_bands)
            _write_matrix(fp, 'DFN2_ERB_FORWARD', forward)
            _write_matrix(fp, 'DFN2_ERB_INVERSE', inverse)
            fp.write("#endif\n")
        print(path)

    unity_error = float(np.max(np.abs(inverse.sum(axis=1) - 1.0)))
    if unity_error > 1e-6:
        raise RuntimeError('inverse ERB matrix is not a partition of unity: %.3g' % unity_error)
    print('shape=%s inverse_unity_max_error=%.3g' % (forward.shape, unity_error))


if __name__ == '__main__':
    main()
