#!/usr/bin/env python3
"""Export the checkpoint-exact ERB maps used by CAGCRN.

This tool lives beside CAGCRN because CAGCRN is the only candidate with an ERB
transform; the others operate directly on FFT bins, where the same export
would be a meaningless identity table.

    python3 export_erb_matrix.py --checkpoint checkpoint.pth \
        --output-dir output --format all
"""

from __future__ import annotations

import argparse
import json
import os
import struct
import sys

import numpy as np

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_AUDIO_ALG_ROOT = os.path.dirname(os.path.dirname(_THIS_DIR))
if _AUDIO_ALG_ROOT not in sys.path:
    sys.path.insert(0, _AUDIO_ALG_ROOT)

from AIAEC._export_common import file_sha256, load_checkpoint_model


MODEL_NAME = 'CAGCRN'


def extract_matrices(model):
    n_bins = model.grid.n_freqs
    low = model.erb.low_bins
    bands = model.erb.merge_matrix.shape[0]
    forward = np.zeros((n_bins, low + bands), dtype=np.float32)
    inverse = np.zeros((low + bands, n_bins), dtype=np.float32)
    forward[:low, :low] = np.eye(low, dtype=np.float32)
    inverse[:low, :low] = np.eye(low, dtype=np.float32)
    forward[low:, low:] = model.erb.merge_matrix.detach().cpu().numpy().T
    inverse[low:, low:] = model.erb.split_matrix.detach().cpu().numpy()
    detail = {'low_identity_bins': int(low), 'high_erb_bands': int(bands)}
    forward = np.ascontiguousarray(forward, dtype='<f4')
    inverse = np.ascontiguousarray(inverse, dtype='<f4')
    if forward.shape[0] != n_bins or inverse.shape != (forward.shape[1], n_bins):
        raise RuntimeError('invalid ERB matrix shapes %s / %s' %
                           (forward.shape, inverse.shape))
    if not np.isfinite(forward).all() or not np.isfinite(inverse).all():
        raise RuntimeError('ERB matrices contain NaN or Inf')
    return forward, inverse, detail


def _write_c_matrix(stream, name, matrix):
    stream.write('static const float %s[%d][%d] = {\n' %
                 (name, matrix.shape[0], matrix.shape[1]))
    for row in matrix:
        stream.write('    {%s},\n' %
                     ', '.join('%.9gf' % float(value) for value in row))
    stream.write('};\n\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--checkpoint', required=True)
    parser.add_argument('--output-dir', required=True)
    parser.add_argument('--format', choices=('bin', 'npy', 'c', 'all'),
                        default='bin')
    args = parser.parse_args()

    model, grid = load_checkpoint_model(MODEL_NAME, args.checkpoint)
    forward, inverse, detail = extract_matrices(model)
    os.makedirs(args.output_dir, exist_ok=True)
    stem = MODEL_NAME.lower() + '_erb'
    metadata = {
        'schema': 'aiaec-erb-matrix-v1',
        'model_family': MODEL_NAME,
        'checkpoint_sha256': file_sha256(args.checkpoint),
        'sample_rate': int(grid.sr),
        'n_fft': int(grid.n_fft),
        'forward_shape': list(forward.shape),
        'inverse_shape': list(inverse.shape),
        'forward_layout': 'fft_bin_major[n_bins][n_features]',
        'inverse_layout': 'feature_major[n_features][n_bins]',
        **detail,
    }
    with open(os.path.join(args.output_dir, stem + '.json'), 'w',
              encoding='utf-8') as stream:
        json.dump(metadata, stream, indent=2, sort_keys=True)
        stream.write('\n')
    if args.format in ('bin', 'all'):
        with open(os.path.join(args.output_dir, stem + '.bin'), 'wb') as stream:
            stream.write(struct.pack('<8sIII', b'AIAECERB', 1,
                                     forward.shape[0], forward.shape[1]))
            stream.write(forward.tobytes())
            stream.write(inverse.tobytes())
    if args.format in ('npy', 'all'):
        np.save(os.path.join(args.output_dir, stem + '_forward.npy'), forward)
        np.save(os.path.join(args.output_dir, stem + '_inverse.npy'), inverse)
    if args.format in ('c', 'all'):
        guard = ('AIAEC_%s_ERB_GENERATED_H' % MODEL_NAME).replace('-', '_')
        with open(os.path.join(args.output_dir, stem + '.h'), 'w',
                  encoding='ascii') as stream:
            stream.write('/* Generated by CAGCRN/export_erb_matrix.py. */\n')
            stream.write('#ifndef %s\n#define %s\n\n' % (guard, guard))
            _write_c_matrix(stream, 'AIAEC_ERB_FORWARD', forward)
            _write_c_matrix(stream, 'AIAEC_ERB_INVERSE', inverse)
            stream.write('#endif\n')
    print('%s: forward=%s inverse=%s' %
          (MODEL_NAME, forward.shape, inverse.shape))


if __name__ == '__main__':
    main()
