#!/usr/bin/env python3
"""Export GTCRN's exact in-graph ERB compression/expansion matrices.

GTCRN already embeds these linear maps in ONNX.  The generated files are for
port validation or a future graph-boundary move; applying them again outside
the current graph would be a functional bug.
"""

import argparse
import configparser
import json
import os
import struct

import numpy as np

from export_onnx import build_stream_model, file_sha256


_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def _write_matrix(fp, name, matrix):
    rows, cols = matrix.shape
    fp.write('static const float %s[%d][%d] = {\n' % (name, rows, cols))
    for row in matrix:
        fp.write('    {%s},\n' % ', '.join('%.9gf' % float(v) for v in row))
    fp.write('};\n\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--config',
                        default=os.path.join(_SCRIPT_DIR, 'config.ini'))
    parser.add_argument('--model', required=True,
                        help='checkpoint whose frozen ERB buffers are exported')
    parser.add_argument('--output-dir', default=None)
    parser.add_argument('--format', choices=('bin', 'npy', 'c', 'all'), default='all')
    args = parser.parse_args()
    cfg = configparser.ConfigParser()
    if not cfg.read(args.config):
        raise FileNotFoundError(args.config)

    stream_model, grid = build_stream_model(args.config, args.model)
    model = stream_model.model
    sr = grid['sr']
    n_fft = grid['n_fft']
    sub1 = grid['sub1']
    sub2 = grid['sub2']
    high_forward = model.erb.erb_fc.weight.detach().numpy().astype('<f4', copy=False)
    high_inverse = model.erb.ierb_fc.weight.detach().numpy().astype('<f4', copy=False)
    n_bins = n_fft // 2 + 1
    n_erb = sub1 + sub2
    forward = np.zeros((n_bins, n_erb), dtype='<f4')
    inverse = np.zeros((n_erb, n_bins), dtype='<f4')
    forward[:sub1, :sub1] = np.eye(sub1, dtype=np.float32)
    forward[sub1:, sub1:] = high_forward.T
    inverse[:sub1, :sub1] = np.eye(sub1, dtype=np.float32)
    inverse[sub1:, sub1:] = high_inverse.T

    output_dir = args.output_dir or cfg.get('paths', 'output_dir', fallback='output')
    os.makedirs(output_dir, exist_ok=True)
    metadata = {
        'schema': 'gtcrn-erb-matrix-v1', 'sample_rate': sr, 'n_fft': n_fft,
        'checkpoint_sha256': file_sha256(args.model),
        'n_bins': n_bins, 'n_erb_features': n_erb,
        'low_identity_bins': sub1, 'high_erb_bands': sub2,
        'graph_boundary': 'inside_onnx',
        'warning': 'Do not apply these matrices outside the current ONNX graph.',
        'forward_layout': 'fft_bin_major[n_bins][n_erb_features]',
        'inverse_layout': 'erb_feature_major[n_erb_features][n_bins]',
    }
    with open(os.path.join(output_dir, 'erb_matrix.json'), 'w', encoding='utf-8') as fp:
        json.dump(metadata, fp, indent=2, sort_keys=True)
        fp.write('\n')
    if args.format in ('bin', 'all'):
        with open(os.path.join(output_dir, 'erb_matrix.bin'), 'wb') as fp:
            fp.write(struct.pack('<iiii', n_bins, n_erb, sub1, sub2))
            fp.write(np.ascontiguousarray(forward).tobytes())
            fp.write(np.ascontiguousarray(inverse).tobytes())
    if args.format in ('npy', 'all'):
        np.save(os.path.join(output_dir, 'erb_forward.npy'), forward)
        np.save(os.path.join(output_dir, 'erb_inverse.npy'), inverse)
    if args.format in ('c', 'all'):
        path = os.path.join(output_dir, 'erb_matrix.h')
        with open(path, 'w', encoding='ascii') as fp:
            fp.write('/* Generated by GTCRN/export_erb_matrix.py; graph already embeds this map. */\n')
            fp.write('#ifndef GTCRN_ERB_MATRIX_GENERATED_H\n#define GTCRN_ERB_MATRIX_GENERATED_H\n\n')
            fp.write('#define GTCRN_ERB_MATRIX_BINS %d\n' % n_bins)
            fp.write('#define GTCRN_ERB_MATRIX_FEATURES %d\n\n' % n_erb)
            _write_matrix(fp, 'GTCRN_ERB_FORWARD', forward)
            _write_matrix(fp, 'GTCRN_ERB_INVERSE', inverse)
            fp.write('#endif\n')
        print(path)
    print('forward=%s inverse=%s (already embedded in ONNX)' %
          (forward.shape, inverse.shape))


if __name__ == '__main__':
    main()
